apiVersion: batch/v1
kind: Job
metadata:
  name: supabase-seed
  namespace: kitaably
  labels:
    app: supabase-seed
spec:
  template:
    metadata:
      name: supabase-seed
      labels:
        app: supabase-seed
    spec:
      containers:
      - name: supabase-seed-container
        image: yashukun/kitaably-bootstrap:latest
        args: [ "seed" ]
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: kitaably-secrets
              key: DATABASE_URL
      restartPolicy: Never
