apiVersion: v1
kind: ConfigMap
metadata:
  name: supabase-kong-config
  namespace: kitaably
data:
  KONG_DATABASE: "off"
  KONG_DECLARATIVE_CONFIG: "/home/kong/kong.yml"
  KONG_PLUGINS: "request-transformer,cors"
  KONG_DNS_ORDER: "LAST,A,CNAME"
  KONG_NGINX_WORKER_PROCESSES: "1"
  KONG_NGINX_PROXY_PROXY_BUFFER_SIZE: "160k"
  KONG_NGINX_PROXY_PROXY_BUFFERS: "64 160k"
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: supabase-kong-config-2
  namespace: kitaably
data:
  kong.yml: |
    _format_version: "1.1"

    services:

    - name: auth-v1-open
      url: http://supabase-auth-service:9999/verify
      routes:
      - name: auth-v1-open
        strip_path: true
        paths: [ /auth/v1/verify ]
      plugins:
      - name: cors

    - name: auth-v1-open-callback
      url: http://supabase-auth-service:9999/callback
      routes:
      - name: auth-v1-open-callback
        strip_path: true
        paths: [ /auth/v1/callback ]
      plugins:
      - name: cors

    - name: auth-v1-open-authorize
      url: http://supabase-auth-service:9999/authorize
      routes:
      - name: auth-v1-open-authorize
        strip_path: true
        paths: [ /auth/v1/authorize ]
      plugins:
      - name: cors

    - name: auth-v1
      url: http://supabase-auth-service:9999/
      routes:
      - name: auth-v1-all
        strip_path: true
        paths: [ /auth/v1/ ]
      plugins:
      - name: cors
      - name: request-transformer
        config:
          add:
            headers:
            - "Authorization: $((headers.authorization) or headers.apikey)"
          replace:
            headers:
            - "Authorization: $((headers.authorization) or headers.apikey)"

    - name: rest-v1
      url: http://supabase-rest-service:3000/
      routes:
      - name: rest-v1-all
        strip_path: true
        paths: [ /rest/v1/ ]
      plugins:
      - name: cors
      - name: request-transformer
        config:
          add:
            headers:
            - "Authorization: $((headers.authorization) or headers.apikey)"
          replace:
            headers:
            - "Authorization: $((headers.authorization) or headers.apikey)"

    - name: storage-v1-s3
      url: http://supabase-storage-service:5000/s3
      routes:
      - name: storage-v1-s3-all
        strip_path: true
        paths: [ /storage/v1/s3/ ]
      plugins:
      - name: cors

    - name: storage-v1
      url: http://supabase-storage-service:5000/
      routes:
      - name: storage-v1-all
        strip_path: true
        paths: [ /storage/v1/ ]
      plugins:
      - name: cors
      - name: request-transformer
        config:
          add:
            headers:
            - "Authorization: $((headers.authorization) or headers.apikey)"
          replace:
            headers:
            - "Authorization: $((headers.authorization) or headers.apikey)"

    - name: pg-meta
      url: http://supabase-meta-service:8080/
      routes:
      - name: pg-meta-all
        strip_path: true
        paths: [ /pg/ ]
      plugins:
      - name: cors
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: supabase-kong
  namespace: kitaably
spec:
  selector:
    matchLabels:
      app: supabase-kong-label
  replicas: 1
  template:
    metadata:
      labels:
        app: supabase-kong-label
    spec:
      containers:
      - name: supabase-kong-container
        image: public.ecr.aws/supabase/kong:2.8.1
        envFrom:
        - configMapRef:
            name: supabase-kong-config
        readinessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        livenessProbe:
          exec:
            command: [ "kong", "health" ]
          initialDelaySeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: kong-config
          mountPath: /home/kong/kong.yml
          subPath: kong.yml
      volumes:
      - name: kong-config
        configMap:
          name: supabase-kong-config-2
      restartPolicy: Always
---

apiVersion: v1
kind: Service
metadata:
  name: supabase-kong-service
  namespace: kitaably
spec:
  selector:
    app: supabase-kong-label
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
